### ISSUE TITLE
这比赛采用pairwise的思路试过没有？ 

### ISSUE THREAD

**Issue by gumanchang** [xv44586/ccf_2020_qa_match#1]
目前最高也就是0.757，看了下前面的同学都是0.8+，感觉很神奇，目前没有太好的思路？ 难道换更大的模型，更多的ensambe？

**Comment by xv44586** [comment]
没试过pairwise，不过有同学用我的其中一个单模型就达到线上0.8+了，可以挑一个模型然后尝试优化性能，参考readme 中最后贴的几篇论文
