### ISSUE TITLE
请问模型融合策略是什么？

### ISSUE THREAD

**Issue by ljch2018** [xv44586/ccf_2020_qa_match#10]
1、对于单个模型，根据不同随机数，训练多个模型；
2、对QA Pair 与 QA Point两类的模型，平均预测的概率作为最终的预测结果？

非常感谢！

**Comment by xv44586** [comment]
单模型可以用kfold，多个不同的模型可以对结果进行投票，我当时是对不同模型进行投票

**Comment by ljch2018** [comment]
> 单模型可以用kfold，多个不同的模型可以对结果进行投票，我当时是对不同模型进行投票

非常感谢！
