### ISSUE TITLE
请问你的模型单模最高多少？是融合了之后上0.8得嘛

### ISSUE THREAD

**Issue by PshySimon** [xv44586/ccf_2020_qa_match#3]
如题，还有就是这次比赛有没有做数据增强呀？感觉这次比赛很多回答都很莫名其妙==

**Comment by xv44586** [comment]
最后一次提交单模型0.806，比赛最后提交的结果是pair + point 模型融合的结果。有做数据增强，具体的后续放上来会。

**Comment by PshySimon** [comment]
大佬太强了，好期待代码==

**Comment by xv44586** [comment]
不是大佬，也是菜鸡，很多方案都没什么提升。
另：这个issue 我先close了
