### ISSUE TITLE
task-adaptive training

### ISSUE THREAD

**Issue by zhangatao** [xv44586/ccf_2020_qa_match#6]
首先祝贺你们取得了第一名的成绩，同时也感谢你们把代码开源出来。我现在有个问题要咨询一下，请问，task-adaptive training和model-adaptive的区别是什么呀，我理解的task-adaptive training是使用比赛的数据，对预训练模型进行再次的训练，得到领域适配的预训练模型，请问我这样的理解对吗？

**Comment by xv44586** [comment]
对的，model-adaptive 是针对qa pair 和 qa point 两种方案的样本格式不同，这里的想法是post-training 和fine-tuning 时格式一样的情况下，性能会更好。所以又用qa pair 格式的样本尝试了post-training 然后fine-tuning qa pair

**Comment by zhangatao** [comment]
感谢回复！
