### ISSUE TITLE
导入NEZHA时报错，

### ISSUE THREAD

**Issue by hungrySharkkk** [xv44586/ccf_2020_qa_match#8]
![image](https://user-images.githubusercontent.com/26642056/105993496-744c5600-60e1-11eb-8905-4dd25f9cf037.png)

运行时报错，检查发现下载的预训练模型里面没有model.ckpt这个文件，请问是需要转换一下吗？谢谢
![image](https://user-images.githubusercontent.com/26642056/105993595-904ff780-60e1-11eb-8d56-29d5144ecdb9.png)

**Comment by hungrySharkkk** [comment]
如果改为model.ckpt-691689，则出现无梯度的错误：

point-post-training-wwm-sop.py

ValueError: No gradients provided for any variable: ['Embedding-Token/embeddings:0'

![image](https://user-images.githubusercontent.com/26642056/105998421-95b04080-60e7-11eb-8d81-df5229515c76.png)

**Comment by xv44586** [comment]
post training的时候需要用tf1.x

**Comment by hungrySharkkk** [comment]
@xv44586  谢谢啦，我再试试

**Comment by hungrySharkkk** [comment]
![image](https://user-images.githubusercontent.com/26642056/106099826-45cc8a80-6176-11eb-8e64-01419a2b47fb.png)
能给一个具体的TF1.X版本吗，我使用TF1.14.0出新这个错误。谢谢

**Comment by xv44586** [comment]
[https://github.com/xv44586/ccf_2020_qa_match/blob/main/requirements-post-training.txt](https://github.com/xv44586/ccf_2020_qa_match/blob/main/requirements-post-training.txt)

**Comment by hungrySharkkk** [comment]
谢谢啦

**Comment by guowhite** [comment]
请问这个问题你能解决吗..我分别用tf 1.14和 tf2.2运行 point-post-training-wwm-sop.py和ccf_2020_qa_match_concat.py 都有这个问题
![image](https://user-images.githubusercontent.com/36331553/106608627-98a3a900-659f-11eb-89ed-12dc68b8f413.png)

**Comment by Lanme** [comment]
请问point-post-training-wwm-sop.py这个训练了多久？epochs=100？
