### ISSUE TITLE
请问训练模型的过程是？

### ISSUE THREAD

**Issue by Lanme** [xv44586/ccf_2020_qa_match#9]
是在nezha 的 Post training 之后加入了对抗、EDA、自蒸馏优化方案进行nezha的 finetune，然后将这几个模型一起融合了么？是没有在baseline上面继续提升么？还是finetune用了baseline的哪个模型？最终是有多少个模型呢？是怎么个融合方式呢？

**Comment by xv44586** [comment]
readme内有博客地址，答案都在博客里
